### ISSUE TITLE
Bugs I've found

### ISSUE THREAD

**Issue by Darktilldawn** [nguyenquyhy/Sponge-Discord#1]
Using /discord broadcast Hmm
http://pastebin.com/mS7ZNQAj

Using /discord login
http://pastebin.com/UZR25a0x

Player logout event and something else
http://pastebin.com/D7dFx5td

Also, if your signed into discord on the server, and on the discord app. When you chat inside the app shouldn't it broadcast in game what's said as well? It doesn't at this moment, I have a default account hooked up as well

And Finally I think, permission nodes to allow the players to login. I do /pex debug and /discord, and /discord login but I only return the same node spongediscord.default

**Comment by nguyenquyhy** [comment]
About the logs, what are you trying to set up? Did you set the Invite code correctly? You will need to put a permanent Invite code in the config file. Probably I will write a more detail instruction in Wiki later.

About broadcasting from Discord to your Minecraft account, I think it should actually broadcast to your own account, so that you will have a complete conversation in both Minecraft and Discord. Imagine that you jump out of Minecraft and send a message from Discord, then you go back to Minecraft to play and receive a reply. Would it be better to see your old messages from Discord in the chat thread as well, so that you can have a complete idea on what the conversation is about?

Finally, I am still working on permission. I am not very familiar with permission in Sponge yet, so I set permission for only `/discord default` command. In that way, servers without PEX can still allow players to login and allow only op to set default account. Later on I will setup proper permission for each command, but thanks for the notice on this.

**Comment by Darktilldawn** [comment]
Yes I've got all the invite codes correct and got the server code correct and it's all linked and looking good. 

Okay so more on the discord chat stuff. It started working now for some reason so looks good. I don't think it should link what your account missed while you were logged out inside Minecraft though only discord. Way to much in-game spam in my opinion if that's what you were talking about.

And for the logs, Basically if your talking in chat every message will send an error for ServerChatEvent not being passed. 

And an error I receive when they are chatting on the server FROM discord is this
http://pastebin.com/yANxWQPd

**Comment by Darktilldawn** [comment]
I'm getting a 403 error attempting to send message, is my login correct. I've double checked all the config and made sure everything was correct and it is. Also you might need to add color support for the prefix on discord messages inside minecraft

**Comment by nguyenquyhy** [comment]
Please try again with 2.0.0 release :).
https://github.com/nguyenquyhy/Sponge-Discord/releases/tag/v2.0.0
