### ISSUE TITLE
Bots messages and prefixes blacklisted are still polluting Minecraft chat. (v2.1.0)

### ISSUE THREAD

**Issue by Axiom1999** [nguyenquyhy/Sponge-Discord#23]
Here is my config file:
`{
  "channels": [
    {
      "minecraft": {
        "chatTemplate": "&8&l`&r &e%a &7> &r%s"
      },
      "discordId": "123456789",
      "discord": {
        "joinedTemplate": "_%s just joined the server_",
        "serverUpMessage": ":exclamation:  Server has started!",
        "serverDownMessage": ":exclamation:  Server has stopped.",
        "leftTemplate": "_%s just left the server_",
        "publicChat": {
          "authenticatedChatTemplate": "`GAME` %s",
          "anonymousChatTemplate": "`GAME | %a:` %s"
        },
        "broadcastTemplate": "_<BROADCAST> %s_"
      }
    }
  ],
  "cancelAllMessagesFromBot": true,
  "prefixBlacklist": [
    "!"
  ],
  "tokenStore": "JSON",
  "minecraftBroadcastTemplate": "&2<BROADCAST> %s",
  "botToken": "1234"
}
`

And yet my Mee6 bot is still sending its messages into the game chat when a command is sent.

I'm running version 2.1.0.

**Comment by VankkaGithub** [comment]
`cancelAllMessagesFromBot` only cancels the messages from the bot of "botToken"

**Comment by nguyenquyhy** [comment]
The setting is to prevent the bot from grab Discord messages from itself and send back to Minecraft.

Can you explain more on your setup? Why do you setup your Mee6 in the channel but does not want Minecraft users to see the message?

**Comment by Axiom1999** [comment]
We have commands in the channel such as '!ip', '!rules', etc. These commands have symbols and big messages. I thought that the blacklist would stop people's command and Bot's sending messages into game.

**Comment by nguyenquyhy** [comment]
@VankkaGithub The approach using botId instead of special character does have an issue: for authenticated user, messages are not sent from bot user, so those are routed back to Minecraft, creating duplication. I think I will go back to using Nonce for this purpose.

@Axiom1999 I think I will change the config `cancelAllMessagesFromBot` will actually cancel messages from all bots. By the way, does that mean you are using Vankka's build. I don't remember publishing any version with this config yet, or am I mistaken?

**Comment by nguyenquyhy** [comment]
`cancelAllMessagesFromBot` is now replaced by `ignoreBots`. Setting this to true will ignore all messages from any Discord bots.
