### ISSUE TITLE
@ Mentions and Server nicks not transferring in game

### ISSUE THREAD

**Issue by stomppnsmash** [nguyenquyhy/Sponge-Discord#24]
If you @ mention someone in discord chat like @Stompp#1234 , it comes into minecraft chat as <@!1234567890>.

Secondary, it also doesn't use the discord server's nick for the user, which would be awesome... Nor does it pickup any kind of nicks in game, but that may require checking for other plugin existence... But the first issue is really the primary concern.

Thanks so much, loving the plugin so far!

**Comment by Mohron** [comment]
I've been looking into both of these issues. Nicks aren't supported at all by the discord API this plugin uses and I'm still having issues with the API resolving the IDs back to names. If I get it working I'll make a PR.

**Comment by Mohron** [comment]
@nguyenquyhy Is there a specific reason you choose to use Javacord vs the other available Discord APIs for Java? I already did most of the code for this a while back but the lack of nickname support has made it basically impossible to finish. I requested support [here](https://github.com/BtoBastian/Javacord/issues/32) but there has been no movement.

**Comment by nguyenquyhy** [comment]
I tried Discord4J before, but they had some dependency on slf4j, which then caused some conflict with some SpongeForge version and spam the console quite a lot. They are also quite against allowing logging in using username and password, so I have to maintain a separate fork with a lot of customization. Javacord turns out to be a better solution for my use case. I will have to make some modification, but they are not very extensive.

Javacord did support getting nickname from mentions. It has a `mentions` array with all the necessary information. I just did not have time to add support for that. Quite easy to add though. I'll do that in next update.
![image](https://cloud.githubusercontent.com/assets/1560418/20860745/b4d09222-b9ba-11e6-9821-3f7aec082624.png)

**Comment by Mohron** [comment]
@nguyenquyhy I've been playing around with the `mentions` array and it's just an array of Users which lack a method to access the nicknames. `Name` is always the user's name they set and not their nickname. `Mention.toString()` also outputs the name even if a nickname is set.

Mentions won't be an issue but Nicknames are whether your talking about the chat template or mentions.

**Comment by Mohron** [comment]
@stomppnsmash This should be fixed via #27
